# Generated by Django 5.1.4 on 2025-01-05 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_records', '0002_reasonforabsence_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='inn',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_phone',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)], verbose_name='Личный телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='snils',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)], verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_phone',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)], verbose_name='Рабочий телефон'),
        ),
    ]
